[package]
name = "portscan"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
indicatif = "0.17"
num_cpus = "1.16"

[dev-dependencies]
testcontainers = "0.23.1"
